"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { ArrowLeft, Archive, CalendarDays, Check, CircleAlert, Edit3, Egg, ShieldCheck, ShoppingCart, Sprout, TrendingDown } from "lucide-react";
import type { BatchDetails, Farm } from "@/domain/types";
import { Badge, Button, Card, SectionHeading } from "@/components/ui";
import { BatchForm } from "@/components/batch-manager";
import { changeBatchStatusAction, type BatchActionState } from "@/app/batches/actions";
import { getBatchHealthHistory } from "@/services/farm-services";

const initialState: BatchActionState = { ok: false, message: "" };

function countdown(days: number) {
  if (days < 0) return "Harvest date passed";
  if (days === 0) return "Harvest today";
  return `${days} days to harvest`;
}

export function BatchDetail({ batch, farm, healthHistory = [] }: { batch: BatchDetails; farm: Farm; healthHistory?: Awaited<ReturnType<typeof getBatchHealthHistory>> }) {
  const [editing, setEditing] = useState(false);
  const [confirming, setConfirming] = useState<"COMPLETED" | "ARCHIVED">();
  const [state, action, pending] = useActionState(changeBatchStatusAction, initialState);
  const statusTone = batch.status === "active" ? "green" : batch.status === "completed" ? "amber" : "neutral";
  if (editing) return <><div className="detail-back"><Link href="/batches"><ArrowLeft size={15} /> Back to batches</Link></div><BatchForm batch={batch} farm={farm} onClose={() => setEditing(false)} /></>;
  return <>
    <div className="detail-back"><Link href="/batches"><ArrowLeft size={15} /> Back to batches</Link></div>
    <div className="page-heading batch-detail-heading"><div><p className="eyebrow">Production cycle <span className="detail-code">{batch.code}</span></p><h1>{batch.name}</h1><p className="heading-subtitle">{batch.breed} · Started {batch.arrivalDate}</p></div><div className="heading-actions"><Button variant="secondary" onClick={() => setEditing(true)}><Edit3 size={16} /> Edit batch</Button>{batch.status === "active" && <Button onClick={() => setConfirming("COMPLETED")}><Check size={16} /> Complete batch</Button>}{batch.status === "completed" && <Button onClick={() => setConfirming("ARCHIVED")}><Archive size={16} /> Archive batch</Button>}</div></div>
    {state.message && <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <CircleAlert size={15} />}{state.message}</div>}
    <div className="detail-hero"><div className="detail-hero-main"><div className="detail-hero-icon"><Sprout size={24} /></div><div><span className="eyebrow">Batch status</span><div className="detail-status-line"><h2>{statusTone === "green" ? "Growing well" : statusTone === "amber" ? "Production complete" : "Archived record"}</h2><Badge tone={statusTone}>{batch.status}</Badge></div><p>{countdown(batch.daysRemaining)} · Expected harvest {batch.harvestDate}</p></div></div><div className="harvest-countdown"><CalendarDays size={17} /><span>Harvest countdown</span><strong>{batch.daysRemaining < 0 ? "Passed" : batch.daysRemaining === 0 ? "Today" : `${batch.daysRemaining} days`}</strong></div></div>
    <div className="detail-stat-grid"><Card><div className="detail-stat-icon detail-green"><Egg size={17} /></div><span>Current birds</span><strong>{batch.currentBirds.toLocaleString()}</strong><small>of {batch.initialBirds.toLocaleString()} started</small></Card><Card><div className="detail-stat-icon detail-red"><TrendingDown size={17} /></div><span>Birds lost</span><strong>{batch.mortality.toLocaleString()}</strong><small>{batch.mortalityRate}% mortality</small></Card><Card><div className="detail-stat-icon detail-amber"><Sprout size={17} /></div><span>Birds sold</span><strong>{batch.birdsSold.toLocaleString()}</strong><small>{batch.soldPercentage}% of starting flock</small></Card><Card><div className="detail-stat-icon detail-blue"><CalendarDays size={17} /></div><span>Flock age</span><strong>Day {batch.ageDays}</strong><small>Since {batch.arrivalDate}</small></Card><Card><div className="detail-stat-icon detail-green"><ShoppingCart size={17} /></div><span>Direct profit</span><strong>{batch.directProfit.toLocaleString()} TZS</strong><small>Revenue less batch expenses</small></Card></div>
    <div className="detail-grid"><Card><SectionHeading eyebrow="Production summary" title="Flock performance" /><div className="performance-list"><div><span>Survival rate</span><strong>{batch.survivalRate}%</strong><div className="performance-track"><i className="track-green" style={{ width: `${batch.survivalRate}%` }} /></div></div><div><span>Mortality rate</span><strong>{batch.mortalityRate}%</strong><div className="performance-track"><i className="track-red" style={{ width: `${Math.min(batch.mortalityRate * 25, 100)}%` }} /></div></div><div><span>Sold percentage</span><strong>{batch.soldPercentage}%</strong><div className="performance-track"><i className="track-amber" style={{ width: `${Math.min(batch.soldPercentage, 100)}%` }} /></div></div></div>{batch.notes && <div className="detail-notes"><strong>Farm notes</strong><p>{batch.notes}</p></div>}</Card><Card><SectionHeading eyebrow="Record history" title="Batch activity" /><div className="batch-activity-list">{batch.activity.length === 0 ? <p className="detail-muted">No recorded activity yet.</p> : batch.activity.map((event) => <div className="batch-activity" key={event.id}><div className={`activity-icon activity-${event.type === "mortality" ? "mortality" : event.type === "sale" ? "sale" : "batch"}`}>{event.type === "mortality" ? <CircleAlert size={15} /> : event.type === "sale" ? <TrendingDown size={15} /> : <Sprout size={15} />}</div><div><strong>{event.title}</strong><span>{event.detail}</span></div><time>{event.date}</time></div>)}</div></Card></div>
    <Card className="batch-health-history"><SectionHeading eyebrow="Flock health" title="Health history" /><div className="batch-activity-list">{healthHistory.length === 0 ? <p className="detail-muted">No health tasks recorded for this batch.</p> : healthHistory.map((task) => <div className="batch-activity" key={task.id}><div className="activity-icon activity-health"><ShieldCheck size={15} /></div><div><strong>{task.name}</strong><span>{task.type} <i /> {task.notes ?? task.instructions ?? task.activityLabel}</span></div><Badge tone={task.status === "completed" ? "green" : task.status === "overdue" ? "red" : "amber"}>{task.status}</Badge><time>{task.scheduledDate}</time></div>)}</div></Card>
    {confirming && <div className="confirm-overlay"><div className="dialog-preview"><div className="dialog-icon">!</div><h3>{confirming === "COMPLETED" ? "Complete this batch?" : "Archive this batch?"}</h3><p>{confirming === "COMPLETED" ? "This keeps the flock history but removes it from active production." : "This preserves the batch for historical reporting."}</p><form action={action} onSubmit={() => setConfirming(undefined)}><input type="hidden" name="batchId" value={batch.id} /><input type="hidden" name="status" value={confirming} /><div className="dialog-actions"><Button type="button" variant="secondary" onClick={() => setConfirming(undefined)}>Cancel</Button><button className="button button-primary" type="submit" disabled={pending}>{pending ? "Saving..." : "Confirm"}</button></div></form></div></div>}
  </>;
}