"use client";

import Link from "next/link";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, BellRing, Bird, CalendarClock, CircleAlert, Clock3, Egg, Plus, Receipt, ShieldCheck, ShoppingCart, Sparkles, Sprout, Wheat } from "lucide-react";
import type { DashboardData, Farm, HealthTask, TodayTask, User } from "@/domain/types";
import { formatCurrency, formatNumber } from "@/lib/format";
import { formatLongDate } from "@/lib/timezone";
import { useLanguage } from "@/lib/i18n/language-provider";
import { greetingKeyForHour } from "@/lib/greeting";
import { useEffect, useState } from "react";
import { Badge, Card, SectionHeading } from "@/components/ui";

const chartTooltip = { contentStyle: { border: "1px solid #dfe9e2", borderRadius: 12, boxShadow: "0 12px 30px rgba(23, 65, 42, .08)", fontSize: 12 }, cursor: { stroke: "#b7cabb", strokeDasharray: "4 4" } };
const categoryColors = ["#166534", "#d99038", "#63a56e", "#e2ad5b", "#8cb8a0", "#a8c4b2"];

function StatCard({ label, value, helper, icon: Icon, tone, trend }: { label: string; value: string; helper: string; icon: typeof Bird; tone: string; trend?: string }) {
  return <Card className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small>{trend && <b>{trend}</b>}{helper}</small></div></Card>;
}

function ChartCard({ title, subtitle, children, className = "" }: { title: string; subtitle: string; children: React.ReactNode; className?: string }) {
  return <Card className={`chart-card ${className}`}><div className="chart-heading"><div><h3>{title}</h3><p>{subtitle}</p></div></div>{children}</Card>;
}

function HealthAlert({ task }: { task: HealthTask }) {
  const tone = task.status === "completed" ? "green" : task.status === "upcoming" ? "amber" : "red";
  const Icon = task.status === "completed" ? ShieldCheck : task.status === "upcoming" ? Clock3 : CircleAlert;
  const label = task.status === "missed" ? "Missed" : task.status === "upcoming" ? "Upcoming" : "Completed";
  return <div className="health-row"><div className={`health-icon health-${tone}`}><Icon size={17} /></div><div className="health-copy"><strong>{task.name}</strong><span>{task.batchCode} <i /> {task.relativeDate}</span></div><Badge tone={tone}>{label}</Badge></div>;
}

function ChickCareNote() {
  return <Card className="chick-care-note"><SectionHeading eyebrow="Early flock care" title="🐥 Important Chick Care Notes" /><div className="chick-care-list"><div className="chick-care-item"><span className="chick-care-icon" aria-hidden="true">💧</span><div><strong>DAY 1</strong><h3>Glucose Water</h3><p>Provide appropriate glucose or electrolyte water for newly arrived chicks according to product instructions or veterinary guidance. Keep the amount within applicable product or farm guidance.</p></div></div><div className="chick-care-item"><span className="chick-care-icon" aria-hidden="true">💊</span><div><strong>DAY 2</strong><h3>Neoxychick + Vitamins</h3><p>Neoxychick and vitamins may be recorded as part of early chick care. Follow the specific product label and veterinary guidance for preparation and use.</p></div></div><div className="chick-care-item"><span className="chick-care-icon" aria-hidden="true">⚕️</span><div><strong>MEDICATION</strong><h3>Tylodox</h3><p>Use Tylodox only when appropriate and according to veterinary or product guidance. It is not automatically required for every flock.</p></div></div><div className="chick-care-item"><span className="chick-care-icon" aria-hidden="true">🍯</span><div><strong>NUTRITION</strong><h3>Molasses</h3><p>Molasses may provide energy and support appetite when appropriately managed, but excessive use can cause digestive upset. Follow appropriate poultry-management guidance.</p></div></div></div><p className="chick-care-disclaimer"><CircleAlert size={15} /> For farm information only. Follow product labels and veterinary guidance for medication and treatment decisions.</p></Card>;
}

export function DashboardView({ data, farm, user }: { data: DashboardData; farm: Farm; user: User }) {
  const totalFeed = data.feedStock.reduce((sum, feed) => sum + feed.remainingKg, 0);
  const { translate: tr } = useLanguage();
  const [greetingKey, setGreetingKey] = useState<string | null>(null);
  useEffect(() => {
    const restore = window.setTimeout(() => setGreetingKey(greetingKeyForHour(new Date().getHours())), 0);
    return () => window.clearTimeout(restore);
  }, []);
  return <>
    <div className="page-heading dashboard-heading"><div><p className="eyebrow">{formatLongDate(new Date(), farm.timezone)} <span className="live-pill"><i /> {tr("Live overview")}</span></p><h1>{greetingKey ? tr(greetingKey, { name: user.name.split(" ")[0] }) : ""}</h1><p className="heading-subtitle">{tr("Here's what's happening across {farm} today.", { farm: farm.name })}</p></div><div className="heading-actions"><Link className="button button-secondary" href="/reports"><ArrowUpRight size={16} /> {tr("View reports")}</Link><Link className="button button-primary" href="/mortality"><Plus size={17} /> {tr("Record activity")}</Link></div></div>
    <div className="today-board"><div className="today-board-heading"><div><span className="today-kicker"><Clock3 size={13} /> {tr("Today's farm tasks")}</span><h2>{tr("What needs your attention?")}</h2><p>{tr("Five small actions keep this production cycle on track.")}</p></div><div className="task-count"><strong>{data.todayTasks.length}</strong><span>{tr("open items")}</span></div></div><div className="today-task-list">{data.todayTasks.map((task) => <TodayTaskCard key={task.id} task={task} />)}</div></div>

    <div className="stats-grid">
      <StatCard label={tr("Active birds")} value={formatNumber(data.stats.activeBirds)} helper={tr("Across all active batches")} icon={Bird} tone="green" trend={`${data.stats.changes.activeBirds} `} />
      <StatCard label="Active batches" value={String(data.stats.activeBatches).padStart(2, "0")} helper="All performing on plan" icon={Egg} tone="mint" trend="" />
      <StatCard label="Total expenses" value={formatCurrency(data.stats.expenses, farm.currency)} helper="This production cycle" icon={Receipt} tone="orange" trend={`${data.stats.changes.expenses} `} />
      <StatCard label="Feed remaining" value={`${formatNumber(totalFeed)} kg`} helper="Across 3 feed types" icon={Wheat} tone="blue" trend="" />
      <StatCard label="Mortality" value={`${data.stats.mortalityRate}%`} helper={`${data.stats.mortality} birds recorded`} icon={CircleAlert} tone="rose" trend={`${data.stats.changes.mortality} `} />
      <StatCard label="Revenue" value={formatCurrency(data.stats.revenue, farm.currency)} helper="This production cycle" icon={ShoppingCart} tone="gold" trend={`${data.stats.changes.revenue} `} />
      <StatCard label="Estimated profit" value={formatCurrency(data.stats.estimatedProfit, farm.currency)} helper="Revenue less expenses" icon={Sparkles} tone="violet" trend={`${data.stats.changes.estimatedProfit} `} />
    </div>

    <ChickCareNote />

    <div className="dashboard-grid charts-row"><ChartCard title="Expenses over time" subtitle="Daily spend, current cycle" className="chart-wide"><ResponsiveContainer width="100%" height={220}><AreaChart data={data.expensesOverTime} margin={{ top: 8, right: 5, left: -22, bottom: 0 }}><defs><linearGradient id="expenseFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#4d9665" stopOpacity={0.25} /><stop offset="100%" stopColor="#4d9665" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7eee9" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} tickFormatter={(value) => `${value / 1000}k`} /><Tooltip {...chartTooltip} formatter={(value) => formatCurrency(Number(value), farm.currency)} /><Area type="monotone" dataKey="expenses" stroke="#287b4a" strokeWidth={2.5} fill="url(#expenseFill)" /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Expenses by category" subtitle="Where your money goes"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={data.expensesByCategory} cx="50%" cy="48%" innerRadius={58} outerRadius={83} paddingAngle={3} dataKey="value" stroke="none">{data.expensesByCategory.map((entry, index) => <Cell key={entry.label} fill={categoryColors[index % categoryColors.length]} />)}</Pie><Tooltip {...chartTooltip} formatter={(value) => formatCurrency(Number(value), farm.currency)} /><text x="50%" y="45%" textAnchor="middle" dominantBaseline="middle" fill="#173b28" fontSize="18" fontWeight="700">{formatCurrency(data.stats.expenses, farm.currency)}</text><text x="50%" y="55%" textAnchor="middle" dominantBaseline="middle" fill="#87968c" fontSize="10">Total expenses</text></PieChart></ResponsiveContainer><div className="chart-legend">{data.expensesByCategory.slice(0, 4).map((entry, index) => <span key={entry.label}><i style={{ background: categoryColors[index] }} />{entry.label}</span>)}</div></ChartCard></div>

    <div className="dashboard-grid charts-row"><ChartCard title="Feed consumption" subtitle="Kilograms consumed this week"><ResponsiveContainer width="100%" height={205}><BarChart data={data.feedConsumption} margin={{ top: 8, right: 4, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e7eee9" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><Tooltip {...chartTooltip} /><Bar dataKey="feed" fill="#d99038" radius={[5, 5, 0, 0]} barSize={20} /></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Mortality trend" subtitle="Recorded birds per day"><ResponsiveContainer width="100%" height={205}><LineChart data={data.mortalityTrend} margin={{ top: 8, right: 6, left: -22, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e7eee9" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><Tooltip {...chartTooltip} /><Line type="monotone" dataKey="mortality" stroke="#d85d4b" strokeWidth={2.5} dot={{ r: 3, fill: "#d85d4b", strokeWidth: 2, stroke: "white" }} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Revenue vs expenses" subtitle="Monthly comparison"><ResponsiveContainer width="100%" height={205}><ComposedChart data={data.revenueVsExpenses} margin={{ top: 8, right: 4, left: -20, bottom: 0 }}><CartesianGrid vertical={false} stroke="#e7eee9" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#7b8c82", fontSize: 11 }} tickFormatter={(value) => `${value / 1000000}m`} /><Tooltip {...chartTooltip} formatter={(value) => formatCurrency(Number(value), farm.currency)} /><Bar dataKey="revenue" fill="#65a978" radius={[4, 4, 0, 0]} barSize={18} /><Bar dataKey="expenses" fill="#e8b25b" radius={[4, 4, 0, 0]} barSize={18} /></ComposedChart></ResponsiveContainer></ChartCard></div>

    <div className="dashboard-grid lower-grid"><Card><SectionHeading eyebrow="Stay ahead" title="Health & medication alerts" action={<Link className="text-link" href="/health">View health log <ArrowUpRight size={14} /></Link>} /><div className="health-list">{data.healthTasks.map((task) => <HealthAlert key={task.id} task={task} />)}</div><div className="alert-note"><CircleAlert size={16} /><span>Health instructions are entered by your farm team or veterinarian.</span></div></Card><Card><SectionHeading eyebrow="Inventory at a glance" title="Feed overview" action={<Link className="text-link" href="/feed">Manage feed <ArrowUpRight size={14} /></Link>} /><div className="feed-list">{data.feedStock.map((feed) => { const percent = Math.min((feed.remainingKg / feed.purchasedKg) * 100, 100); const low = feed.remainingKg < feed.thresholdKg; return <div className="feed-item" key={feed.id}><div className="feed-item-head"><div><span className="feed-name"><Wheat size={14} />{feed.type}</span><small>{formatNumber(feed.consumedKg)} kg consumed</small></div><strong>{formatNumber(feed.remainingKg)} <small>kg</small></strong></div><div className="progress-track"><span className={low ? "low" : ""} style={{ width: `${percent}%` }} /></div>{low && <p className="low-stock"><CircleAlert size={13} /> Below {feed.thresholdKg} kg threshold</p>}</div> })}</div></Card></div>

    <div className="dashboard-grid lower-grid"><Card><SectionHeading eyebrow="Production cycle" title="Active batches" action={<Link className="text-link" href="/batches">All batches <ArrowUpRight size={14} /></Link>} /><div className="batch-list">{data.batches.map((batch) => <div className="batch-row" key={batch.id}><div className="batch-avatar">{batch.code.slice(-3)}</div><div className="batch-info"><strong>{batch.code}</strong><span>{formatNumber(batch.currentBirds)} birds <i /> Day {batch.ageDays}</span></div><div className="batch-metric"><span>Mortality</span><strong>{batch.mortalityRate}%</strong></div><div className="batch-metric harvest"><span>Harvest</span><strong>{batch.daysRemaining} days</strong></div>{batch.daysRemaining <= 21 && <Badge tone="amber">Soon</Badge>}<ArrowUpRight className="batch-arrow" size={16} /></div>)}</div></Card><Card><SectionHeading eyebrow="Farm pulse" title="Recent activity" action={<Link className="text-link" href="/reports">View all <ArrowUpRight size={14} /></Link>} /><div className="activity-list">{data.activities.slice(0, 5).map((activity) => <div className="activity-row" key={activity.id}><div className={`activity-icon activity-${activity.type}`}>{activity.type === "feed" ? <Wheat size={15} /> : activity.type === "mortality" ? <CircleAlert size={15} /> : activity.type === "health" ? <ShieldCheck size={15} /> : activity.type === "sale" ? <ShoppingCart size={15} /> : activity.type === "expense" ? <Receipt size={15} /> : <Sprout size={15} />}</div><div><strong>{activity.title}</strong><span>{activity.description}</span></div><time>{activity.time}</time></div>)}</div></Card></div>

    <div className="dashboard-grid lower-grid"><NotificationPreview data={data} /><Card className="mortality-summary"><SectionHeading eyebrow="Flock health" title="Mortality watch" action={<Link className="text-link" href="/mortality">Review records <ArrowUpRight size={14} /></Link>} /><div className="mortality-number"><div><strong>{data.stats.mortalityRate}%</strong><span>current mortality</span></div><div className="mortality-change"><ArrowUpRight size={14} /> {data.stats.changes.mortality} vs last cycle</div></div><div className="mortality-track"><span style={{ width: `${Math.min(data.stats.mortalityRate * 25, 100)}%` }} /></div><div className="mortality-facts"><div><strong>{data.stats.deathsToday}</strong><span>deaths today</span></div><div><strong>{data.stats.deathsThisWeek}</strong><span>deaths this week</span></div></div><p className="mortality-note"><CircleAlert size={14} /> {data.stats.deathsToday ? `${data.stats.deathsToday} birds recorded today.` : "No mortality recorded today."}</p></Card></div>

    <Card className="profit-card"><div><span className="eyebrow">Profit trend</span><h2>Building a healthier bottom line.</h2><p>Your estimated profit is up <strong>{data.stats.changes.estimatedProfit}</strong> from the previous production cycle.</p><Link className="text-link" href="/reports">Explore profitability <ArrowUpRight size={14} /></Link></div><div className="profit-chart"><ResponsiveContainer width="100%" height={120}><AreaChart data={data.profitTrend}><defs><linearGradient id="profitFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#a9d4b0" stopOpacity={0.45} /><stop offset="100%" stopColor="#a9d4b0" stopOpacity={0} /></linearGradient></defs><Area dataKey="profit" type="monotone" stroke="#d9f0d9" strokeWidth={2.5} fill="url(#profitFill)" /><YAxis hide /><XAxis dataKey="label" hide /></AreaChart></ResponsiveContainer></div></Card>
  </>;
}
function TodayTaskCard({ task }: { task: TodayTask }) {
  const Icon = task.type === "health" ? ShieldCheck : task.type === "feed" ? Wheat : task.type === "harvest" ? CalendarClock : CircleAlert;
  const statusLabel = task.status === "open" ? "Open" : task.status === "scheduled" ? "Scheduled" : "Monitoring";
  const actionHref = task.type === "health" ? "/health" : task.type === "feed" ? "/feed" : task.type === "harvest" ? "/batches" : "/mortality";
  return <div className={`today-task task-${task.priority}`}><div className="today-task-icon"><Icon size={17} /></div><div className="today-task-copy"><strong>{task.title}</strong><span>{task.detail}{task.relatedCode && <> <i /> {task.relatedCode}</>}</span><small className="task-status">{statusLabel}</small></div><div className="today-task-due"><small>{task.priority === "urgent" ? "Urgent" : task.priority === "attention" ? "Attention" : "Plan ahead"}</small><strong>{task.dueLabel}</strong></div><Link className="task-action" href={actionHref}>{task.actionLabel}</Link><ArrowUpRight className="task-arrow" size={15} /></div>;
}
function NotificationPreview({ data }: { data: DashboardData }) {
  return <Card className="notification-preview"><SectionHeading eyebrow="Notification center" title="Keep the flock moving" action={<Link className="text-link" href="/notifications">Open inbox <ArrowUpRight size={14} /></Link>} /><div className="notification-list">{data.notifications.slice(0, 3).map((notification) => <div className="notification-row" key={notification.id}><div className={`notification-icon notification-${notification.status}`}><BellRing size={15} /></div><div><strong>{notification.title}</strong><span>{notification.message}</span></div><time>{notification.time}</time></div>)}</div></Card>;
}
