"use client";

import { useActionState, useState } from "react";
import { Check, Plus, Search, X } from "lucide-react";
import type { Batch, Expense, Farm } from "@/domain/types";
import { expenseAction } from "@/app/expenses/actions";
import { Badge, Button, Card, EmptyState, FormField, SectionHeading } from "@/components/ui";

type Option = { id: string; name: string };
const empty = { ok: false, message: "" };
const paymentLabels: Record<string, string> = { CASH: "Cash", MOBILE_MONEY: "Mobile Money", BANK_TRANSFER: "Bank Transfer", CARD: "Card", CREDIT: "Credit", OTHER: "Other" };
function money(value: number, currency: string) { return new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 0 }).format(value).replace("TZS", "TZS "); }
function Feedback({ state }: { state: { ok: boolean; message: string } }) { return state.message ? <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <X size={15} />}{state.message}</div> : null; }

function ExpenseForm({ categories, suppliers, batches, expense, onClose }: { categories: Option[]; suppliers: Option[]; batches: Batch[]; expense?: Expense; onClose: () => void }) {
  const [state, action, pending] = useActionState(expenseAction, empty);
  return <Card className="phase4-form"><div className="form-card-heading"><div><p className="eyebrow">Farm finances</p><h2>{expense ? "Edit expense" : "Record expense"}</h2><p>Amounts are calculated and validated on the server.</p></div><button className="icon-button" onClick={onClose} aria-label="Close expense form"><X size={18} /></button></div><Feedback state={state} /><form action={action} className="batch-form"><input type="hidden" name="expenseId" value={expense?.id ?? ""} /><div className="form-grid"><FormField label="Description"><input name="description" defaultValue={expense?.description} required placeholder="e.g. Feed delivery" /></FormField><FormField label="Amount"><input name="amount" type="number" min="0.01" step="0.01" defaultValue={expense?.amount} required placeholder="0" /></FormField><FormField label="Category"><select name="categoryId" defaultValue={categories.find((item) => item.name === expense?.category)?.id}>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Supplier"><select name="supplierId" defaultValue=""><option value="">No supplier</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Payment method"><select name="paymentMethod" defaultValue={expense?.paymentMethod ?? "CASH"}>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></FormField><FormField label="Date"><input type="date" name="date" defaultValue={expense?.date ?? "2026-09-09"} required /></FormField><FormField label="Batch"><select name="batchId" defaultValue=""><option value="">Farm-wide</option>{batches.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select></FormField></div><FormField label="Notes"><textarea name="notes" defaultValue={expense?.notes} rows={3} placeholder="Optional notes" /></FormField><div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "Saving..." : expense ? "Save changes" : "Record expense"}</button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></Card>;
}

export function ExpenseManager({ farm, expenses, categories, suppliers, batches, summary }: { farm: Farm; expenses: Expense[]; categories: Option[]; suppliers: Option[]; batches: Batch[]; summary: { total: number; thisMonth: number; today: number; count: number; byCategory: Array<{ label: string; value: number }> } }) {
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [payment, setPayment] = useState("all"); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<Expense>();
  const filtered = expenses.filter((item) => `${item.description} ${item.category} ${item.supplier}`.toLowerCase().includes(query.toLowerCase()) && (category === "all" || item.category === category) && (payment === "all" || item.paymentMethod === payment));
  return <><div className="page-heading"><div><p className="eyebrow">Farm finances</p><h1>Expenses</h1><p className="heading-subtitle">A clear record of what the farm spends and where it goes.</p></div><Button onClick={() => { setEditing(undefined); setFormOpen(true); }}><Plus size={17} /> Record expense</Button></div><div className="batch-summary-grid expense-summary"><Card><span>Total expenses</span><strong>{money(summary.total, farm.currency)}</strong><small>All recorded time</small></Card><Card><span>This month</span><strong>{money(summary.thisMonth, farm.currency)}</strong><small>Current production cycle</small></Card><Card><span>Today</span><strong>{money(summary.today, farm.currency)}</strong><small>{summary.count} total records</small></Card></div>{formOpen && <ExpenseForm categories={categories} suppliers={suppliers} batches={batches} expense={editing} onClose={() => setFormOpen(false)} />}<Card className="phase4-list-card"><SectionHeading eyebrow="Expense register" title="Recent expenses" action={<span className="batch-list-meta">{filtered.length} shown</span>} /><div className="batch-toolbar"><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search expenses" aria-label="Search expenses" /></label><select className="filter-select" value={category} onChange={(event) => setCategory(event.target.value)} aria-label="Filter by category"><option value="all">All categories</option>{categories.map((item) => <option key={item.id} value={item.name}>{item.name}</option>)}</select><select className="filter-select" value={payment} onChange={(event) => setPayment(event.target.value)} aria-label="Filter by payment method"><option value="all">All payments</option>{Object.entries(paymentLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>{filtered.length === 0 ? <EmptyState title="No expenses found" message="Try a different filter or record the first expense for this farm." action={<Button onClick={() => setFormOpen(true)}><Plus size={16} /> Record expense</Button>} /> : <div className="expense-list">{filtered.map((item) => <div className="expense-row" key={item.id}><div className="expense-date">{item.date.slice(5).replace("-", "/")}</div><div className="expense-main"><strong>{item.description}</strong><span>{item.category} <i /> {item.supplier || "No supplier"}{item.batchCode && <> <i /> {item.batchCode}</>}</span></div><Badge tone="neutral">{paymentLabels[item.paymentMethod ?? "OTHER"] ?? item.paymentMethod}</Badge><strong className="expense-amount">{money(item.amount, farm.currency)}</strong><button className="row-action-text" onClick={() => { setEditing(item); setFormOpen(true); }}>Edit</button></div>)}</div>}</Card></>;
}