"use client";

import { useActionState, useState } from "react";
import { AlertTriangle, Check, Edit3, PackagePlus, Trash2, X } from "lucide-react";
import type { Batch, Farm, FeedStock, FeedTransactionRecord } from "@/domain/types";
import { deleteFeedTransactionAction, feedTransactionAction } from "@/app/feed/actions";
import { Badge, Button, Card, EmptyState, FormField, SectionHeading } from "@/components/ui";

const empty = { ok: false, message: "" };
type Product = { id: string; name: string; type: string; lowStockThreshold: number };
type Supplier = { id: string; name: string };
function Feedback({ state }: { state: { ok: boolean; message: string } }) { return state.message ? <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <X size={15} />}{state.message}</div> : null; }

function FeedTransactionForm({ products, suppliers, batches, transaction, onClose }: { products: Product[]; suppliers: Supplier[]; batches: Batch[]; transaction?: FeedTransactionRecord; onClose: () => void }) {
  const [state, action, pending] = useActionState(feedTransactionAction, empty);
  const [type, setType] = useState(transaction?.type ?? "PURCHASE");
  const product = products.find((item) => item.id === transaction?.productId);
  const supplier = suppliers.find((item) => item.name === transaction?.supplier);
  const batch = batches.find((item) => item.code === transaction?.batchCode);
  return <Card className="phase4-form"><div className="form-card-heading"><div><p className="eyebrow">Inventory ledger</p><h2>{transaction ? "Edit feed movement" : "Record feed movement"}</h2><p>Purchases add stock; consumption reduces it.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close feed transaction form"><X size={18} /></button></div><Feedback state={state} /><form action={action} className="batch-form"><input type="hidden" name="transactionId" value={transaction?.id ?? ""} /><div className="form-grid"><FormField label="Transaction type"><select name="type" value={type} onChange={(event) => setType(event.target.value as "PURCHASE" | "CONSUMPTION" | "ADJUSTMENT")}><option value="PURCHASE">Purchase</option><option value="CONSUMPTION">Consumption</option><option value="ADJUSTMENT">Adjustment</option></select></FormField><FormField label="Feed product"><select name="productId" required defaultValue={product?.id ?? products[0]?.id ?? ""}>{products.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.type}</option>)}</select></FormField><FormField label="Quantity"><input name="quantity" type="number" min="0.001" step="0.001" defaultValue={transaction?.quantity ?? ""} required /></FormField><FormField label="Unit"><input name="unit" defaultValue={transaction?.unit ?? "kg"} required /></FormField><FormField label="Date"><input name="date" type="date" defaultValue={transaction?.date ?? "2026-09-11"} required /></FormField><FormField label="Supplier"><select name="supplierId" defaultValue={supplier?.id ?? ""}><option value="">No supplier</option>{suppliers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Batch"><select name="batchId" defaultValue={batch?.id ?? ""}><option value="">Farm-wide</option>{batches.map((item) => <option key={item.id} value={item.id}>{item.code}</option>)}</select></FormField><FormField label="Unit price"><input name="unitPrice" type="number" min="0" step="0.01" defaultValue={transaction?.unitPrice ?? ""} required={type === "PURCHASE"} /></FormField></div><FormField label="Reference / reason"><textarea name="notes" defaultValue={transaction?.notes ?? ""} rows={3} /></FormField><div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "Saving..." : transaction ? "Save changes" : "Record movement"}</button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></Card>;
}

function FeedRow({ item, onEdit }: { item: FeedTransactionRecord; onEdit: () => void }) {
  const [state, action, pending] = useActionState(deleteFeedTransactionAction, empty);
  function remove() { if (window.confirm(`Delete ${item.type.toLowerCase()} for ${item.productName}?`)) { const formData = new FormData(); formData.set("transactionId", item.id); void action(formData); } }
  return <div className="feed-ledger-row"><div><strong>{item.productName}</strong><span>{item.date} <i /> {item.notes || item.type.toLowerCase()}</span></div><Badge tone={item.type === "PURCHASE" ? "green" : item.type === "CONSUMPTION" ? "amber" : "neutral"}>{item.type}</Badge><strong className={item.type === "CONSUMPTION" ? "metric-risk" : ""}>{item.type === "CONSUMPTION" ? "-" : "+"}{item.quantity} {item.unit}</strong><button type="button" className="icon-button" onClick={onEdit} aria-label={`Edit feed movement for ${item.productName}`}><Edit3 size={15} /></button><button type="button" className="icon-button" onClick={remove} disabled={pending} aria-label={`Delete feed movement for ${item.productName}`}><Trash2 size={15} /></button>{state.message && <small className="health-row-feedback">{state.message}</small>}</div>;
}

export function FeedManager({ stock, transactions, products, suppliers, batches, summary }: { farm: Farm; stock: FeedStock[]; transactions: FeedTransactionRecord[]; products: Product[]; suppliers: Supplier[]; batches: Batch[]; summary: { totalRemainingKg: number; lowStockCount: number } }) {
  const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<FeedTransactionRecord>();
  function create() { setEditing(undefined); setFormOpen(true); }
  return <><div className="page-heading"><div><p className="eyebrow">Inventory control</p><h1>Feed management</h1><p className="heading-subtitle">Stock is calculated from every purchase, usage, and adjustment.</p></div><Button onClick={create}><PackagePlus size={17} /> Record movement</Button></div><div className="batch-summary-grid feed-summary"><Card><span>Total feed remaining</span><strong>{summary.totalRemainingKg.toLocaleString()} <small>kg</small></strong><small>{summary.lowStockCount} low-stock products</small></Card>{stock.map((item) => <Card key={item.id}><span>{item.type} feed</span><strong>{item.remainingKg.toLocaleString()} <small>kg</small></strong><small className={item.remainingKg <= item.thresholdKg ? "metric-risk" : ""}>{item.remainingKg <= item.thresholdKg ? "Low stock" : "Good stock"}</small></Card>)}</div>{formOpen && <FeedTransactionForm products={products} suppliers={suppliers} batches={batches} transaction={editing} onClose={() => setFormOpen(false)} />}<div className="feed-layout"><Card><SectionHeading eyebrow="Current inventory" title="Feed stock" />{stock.length === 0 ? <EmptyState title="No feed products" message="Starter, Grower, and Finisher feed products are configured for this farm." /> : <div className="feed-stock-list">{stock.map((item) => { const low = item.remainingKg <= item.thresholdKg; const percent = item.purchasedKg ? Math.max(0, Math.min(100, item.remainingKg / item.purchasedKg * 100)) : 0; return <div className="feed-stock-row" key={item.id}><div className="feed-stock-name"><div className="feed-product-icon"><PackagePlus size={16} /></div><div><strong>{item.type} feed</strong><span>{item.productName}</span></div></div><div className="feed-stock-number"><strong>{item.remainingKg.toLocaleString()} kg</strong><small>{low ? <><AlertTriangle size={12} /> Low stock</> : "Good"}</small></div><div className="progress-track"><span className={low ? "low" : ""} style={{ width: `${percent}%` }} /></div></div>; })}</div>}</Card><Card><SectionHeading eyebrow="Ledger" title="Transaction history" />{transactions.length === 0 ? <EmptyState title="No transactions" message="Feed purchases and usage will appear here." /> : <div className="feed-ledger">{transactions.map((item) => <FeedRow key={item.id} item={item} onEdit={() => { setEditing(item); setFormOpen(true); }} />)}</div>}</Card></div></>;
}