"use client";

import { useActionState, useState } from "react";
import { Check, Edit3, Plus, Search, ShieldCheck, X } from "lucide-react";
import type { Batch, HealthSummary, HealthTask } from "@/domain/types";
import { healthTaskAction, completeHealthTaskAction } from "@/app/health/actions";
import { Badge, Button, Card, EmptyState, FormField, SectionHeading } from "@/components/ui";

const empty = { ok: false, message: "" };
function tone(status: HealthTask["status"]) { return status === "completed" ? "green" : status === "overdue" || status === "missed" ? "red" : "amber"; }
function label(status: HealthTask["status"]) { return status === "completed" ? "Completed" : status === "overdue" ? "Overdue" : status === "missed" ? "Missed" : "Pending"; }
function Feedback({ state }: { state: { ok: boolean; message: string } }) { return state.message ? <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <X size={15} />}{state.message}</div> : null; }

function HealthForm({ batches, task, onClose }: { batches: Batch[]; task?: HealthTask; onClose: () => void }) {
  const [state, action, pending] = useActionState(healthTaskAction, empty);
  return <Card className="phase4-form"><div className="form-card-heading"><div><p className="eyebrow">Flock health</p><h2>{task ? "Edit health task" : "New health task"}</h2><p>Enter schedules and instructions provided by your farm team or veterinarian.</p></div><button className="icon-button" onClick={onClose} aria-label="Close health task form"><X size={18} /></button></div><Feedback state={state} /><form action={action} className="batch-form"><input type="hidden" name="taskId" value={task?.id ?? ""} /><div className="form-grid"><FormField label="Task name"><input name="title" defaultValue={task?.name ?? ""} placeholder="e.g. Newcastle vaccination" required /></FormField><FormField label="Type"><select name="type" defaultValue={task?.type === "Vaccine" ? "VACCINATION" : task?.type === "Medicine" ? "MEDICINE" : "OTHER"}><option value="VACCINATION">Vaccination</option><option value="MEDICINE">Medicine / treatment</option><option value="OTHER">Other health task</option></select></FormField><FormField label="Batch"><select name="batchId" defaultValue={task?.batchId ?? ""} required><option value="">Select batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.code}</option>)}</select></FormField><FormField label="Scheduled date and time"><input type="datetime-local" name="scheduledAt" defaultValue={task?.scheduledAt?.slice(0, 16) ?? "2026-09-10T09:00"} required /></FormField><FormField label="Status"><select name="status" defaultValue={task?.status === "completed" ? "COMPLETED" : "UPCOMING"}><option value="UPCOMING">Pending</option><option value="COMPLETED">Completed</option></select></FormField></div><FormField label="Instructions / notes"><textarea name="instructions" defaultValue={task?.instructions ?? ""} rows={3} placeholder="Farmer-entered or veterinarian-provided instructions" /></FormField><FormField label="Internal notes"><textarea name="notes" defaultValue={task?.notes ?? ""} rows={2} placeholder="Optional notes" /></FormField><div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "Saving..." : task ? "Save changes" : "Create task"}</button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></Card>;
}

export function HealthManager({ batches, tasks, summary }: { batches: Batch[]; tasks: HealthTask[]; summary: HealthSummary }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState<HealthTask>();
  const filtered = tasks.filter((task) => `${task.name} ${task.batchCode} ${task.type}`.toLowerCase().includes(query.toLowerCase()) && (filter === "all" || (filter === "pending" && task.status === "upcoming") || (filter === "completed" && task.status === "completed") || (filter === "overdue" && (task.status === "overdue" || task.status === "missed")) || (filter === "vaccination" && task.type === "Vaccine") || (filter === "treatment" && task.type !== "Vaccine")));
  return <><div className="page-heading"><div><p className="eyebrow">Flock health</p><h1>Medicine & vaccines</h1><p className="heading-subtitle">Keep health tasks, schedules, and completion history clear and farmer-entered.</p></div><Button onClick={() => { setEditing(undefined); setFormOpen(true); }}><Plus size={17} /> New health task</Button></div><div className="batch-summary-grid health-summary"><Card><span>Total tasks</span><strong>{summary.total}</strong><small>All health records</small></Card><Card><span>Pending</span><strong>{summary.pending}</strong><small>Scheduled tasks</small></Card><Card><span>Overdue</span><strong className={summary.overdue ? "metric-risk" : ""}>{summary.overdue}</strong><small>Needs review</small></Card><Card><span>Completed</span><strong>{summary.completed}</strong><small>Persisted history</small></Card></div>{formOpen && <HealthForm batches={batches} task={editing} onClose={() => setFormOpen(false)} />}<Card className="phase4-list-card"><SectionHeading eyebrow="Health register" title="All health tasks" action={<span className="batch-list-meta">{filtered.length} shown</span>} /><div className="batch-toolbar"><label className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search health tasks" aria-label="Search health tasks" /></label><select className="filter-select" value={filter} onChange={(event) => setFilter(event.target.value)} aria-label="Filter health tasks"><option value="all">All tasks</option><option value="pending">Pending</option><option value="completed">Completed</option><option value="overdue">Overdue</option><option value="vaccination">Vaccinations</option><option value="treatment">Medicine / treatment</option></select></div>{filtered.length === 0 ? <EmptyState title="No health tasks found" message="Try another filter or create the first task for your flock." action={<Button onClick={() => setFormOpen(true)}><Plus size={16} /> New health task</Button>} /> : <div className="health-task-list">{filtered.map((task) => <HealthTaskRow key={task.id} task={task} onEdit={() => { setEditing(task); setFormOpen(true); }} />)}</div>}</Card></>;
}

function HealthTaskRow({ task, onEdit }: { task: HealthTask; onEdit: () => void }) {
  const [state, action, pending] = useActionState(completeHealthTaskAction, empty);
  return <div className="health-task-row"><div className={`health-task-icon health-${tone(task.status)}`}><ShieldCheck size={17} /></div><div className="health-task-main"><strong>{task.name}</strong><span>{task.type} <i /> {task.batchCode}</span><small>{task.scheduledDate} · {task.relativeDate}</small></div><Badge tone={tone(task.status)}>{label(task.status)}</Badge><div className="health-task-actions">{task.status !== "completed" && <form action={action}><input type="hidden" name="taskId" value={task.id} /><button className="row-action-text" disabled={pending}>{pending ? "..." : "Complete"}</button></form>}<button className="icon-button" onClick={onEdit} aria-label={`Edit ${task.name}`}><Edit3 size={15} /></button></div>{state.message && <span className="health-row-feedback">{state.message}</span>}</div>;
}