"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { BellRing, CalendarClock, CircleAlert, Package, ShieldCheck } from "lucide-react";
import type { Notification } from "@/domain/types";
import { markAllNotificationsReadAction, markNotificationReadAction } from "@/app/notifications/actions";
import { Badge, Button, Card, SectionHeading } from "@/components/ui";

const empty = { ok: false, message: "" };
function notificationIcon(notification: Notification) { if (notification.type === "feed") return <Package size={17} />; if (notification.type === "harvest") return <CalendarClock size={17} />; if (notification.status === "completed") return <ShieldCheck size={17} />; return <CircleAlert size={17} />; }
function notificationTone(notification: Notification) { if (notification.status === "missed" || notification.status === "warning") return "red"; if (notification.status === "upcoming") return "amber"; return "green"; }
function destination(notification: Notification) { if (notification.type === "health") return "/health"; if (notification.type === "feed") return "/feed"; if (notification.batchCode) return "/batches"; return undefined; }

function NotificationRecord({ notification }: { notification: Notification }) {
  const [state, action, pending] = useActionState(markNotificationReadAction, empty);
  const tone = notificationTone(notification); const target = destination(notification); const label = notification.status === "missed" ? "Missed" : notification.status === "warning" ? "Attention" : notification.status === "upcoming" ? "Upcoming" : "Completed";
  return <div className={`notification-record ${notification.read ? "notification-read" : ""}`}><div className={`notification-record-icon notification-record-${tone}`}>{notificationIcon(notification)}</div><div className="notification-record-copy"><div><strong>{notification.title}</strong>{!notification.read && <span className="unread-dot" />}</div><p>{notification.message}</p><small>{notification.time}{notification.batchCode && <> <i /> {notification.batchCode}</>}</small></div><Badge tone={tone}>{label}</Badge><div className="notification-record-actions">{target && <Link className="row-action-text" href={target}>Open</Link>}{!notification.read && <form action={action}><input type="hidden" name="notificationId" value={notification.id} /><button className="row-action-text" disabled={pending}>{pending ? "..." : "Read"}</button></form>}</div>{state.message && !state.ok && <small className="field-error">{state.message}</small>}</div>;
}

export function NotificationCenterClient({ notifications }: { notifications: Notification[] }) {
  const [filter, setFilter] = useState("all"); const [state, markAll, pending] = useActionState(markAllNotificationsReadAction, empty);
  const unread = notifications.filter((item) => !item.read).length;
  const filtered = notifications.filter((item) => filter === "all" || (filter === "unread" && !item.read) || (filter === "read" && item.read) || (filter === "health" && item.type === "health") || (filter === "feed" && item.type === "feed") || (filter === "other" && !["health", "feed"].includes(item.type)));
  return <><div className="page-heading"><div><p className="eyebrow">Stay informed</p><h1>Notification center</h1><p className="heading-subtitle">A calm view of the tasks, risks, and dates that deserve your attention.</p></div><form action={markAll}><Button variant="secondary" disabled={!unread || pending}><BellRing size={16} /> {unread ? `${unread} unread` : "All read"}</Button></form></div>{state.message && <div className="form-feedback feedback-success" role="status">{state.message}</div>}<div className="notification-layout"><Card className="notification-inbox"><SectionHeading eyebrow="Farm pulse" title="All notifications" action={<span className="batch-list-meta">{filtered.length} shown</span>} /><div className="notification-filters"><button className={filter === "all" ? "filter-active" : ""} onClick={() => setFilter("all")}>All <b>{notifications.length}</b></button><button className={filter === "unread" ? "filter-active" : ""} onClick={() => setFilter("unread")}>Unread <b>{unread}</b></button><button className={filter === "read" ? "filter-active" : ""} onClick={() => setFilter("read")}>Read</button><button className={filter === "health" ? "filter-active" : ""} onClick={() => setFilter("health")}>Health</button><button className={filter === "feed" ? "filter-active" : ""} onClick={() => setFilter("feed")}>Feed</button><button className={filter === "other" ? "filter-active" : ""} onClick={() => setFilter("other")}>Other</button></div><div className="notification-records">{filtered.length ? filtered.map((notification) => <NotificationRecord key={notification.id} notification={notification} />) : <div className="empty-state"><div className="empty-state-mark">+</div><h3>No notifications here</h3><p>There are no notifications in this view.</p></div>}</div></Card><Card className="notification-guide"><div className="notification-guide-icon"><BellRing size={19} /></div><p className="eyebrow">In-app alerts</p><h2>Designed for a quieter farm day.</h2><p>Health alerts are generated from persisted task dates and completion state. Read status is saved to PostgreSQL.</p><div className="notification-rule"><span>Unread</span><strong>{unread}</strong></div><div className="notification-rule"><span>Channels</span><strong>In-app</strong></div></Card></div></>;
}
