"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { Check, Edit3, Plus, Search, ShoppingCart, Trash2, X } from "lucide-react";
import type { Batch, Farm, PaymentSummary, Sale } from "@/domain/types";
import { deleteSaleAction, saleAction } from "@/app/sales/actions";
import { Badge, Button, Card, EmptyState, FormField, SectionHeading } from "@/components/ui";

type Customer = { id: string; name: string; phone?: string | null };
const empty = { ok: false, message: "" };
function money(value: number, currency: string) { return new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 0 }).format(value).replace("TZS", "TZS "); }
function Feedback({ state }: { state: { ok: boolean; message: string } }) { return state.message ? <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <X size={15} />}{state.message}</div> : null; }

function SaleForm({ batches, customers, sale, onClose }: { batches: Batch[]; customers: Customer[]; sale?: Sale; onClose: () => void }) {
  const [state, action, pending] = useActionState(saleAction, empty);
  const [mode, setMode] = useState(sale?.pricingMode ?? "PER_KG");
  const selectedBatch = batches.find((batch) => batch.code === sale?.batchCode);
  const customer = customers.find((item) => item.name === sale?.buyer);
  return <Card className="phase4-form"><div className="form-card-heading"><div><p className="eyebrow">Farm revenue</p><h2>{sale ? "Edit sale" : "Record sale"}</h2><p>Revenue is calculated and validated on the server.</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close sale form"><X size={18} /></button></div><Feedback state={state} /><form action={action} className="batch-form"><input type="hidden" name="saleId" value={sale?.id ?? ""} /><div className="form-grid"><FormField label="Batch"><select name="batchId" required defaultValue={selectedBatch?.id ?? ""}><option value="">Select batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.code} · {batch.currentBirds.toLocaleString()} available</option>)}</select></FormField><FormField label="Customer"><select name="customerId" defaultValue={customer?.id ?? ""}><option value="">Direct sale</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></FormField><FormField label="Sale date"><input type="date" name="date" defaultValue={sale?.date ?? "2026-09-10"} required /></FormField><FormField label="Birds sold"><input type="number" name="birdsSold" min="1" defaultValue={sale?.birds ?? ""} required /></FormField><FormField label="Pricing mode"><select name="pricingMode" value={mode} onChange={(event) => setMode(event.target.value as "PER_KG" | "PER_BIRD")}><option value="PER_KG">Per kilogram</option><option value="PER_BIRD">Per bird</option></select></FormField>{mode === "PER_KG" ? <><FormField label="Total weight (kg)"><input type="number" name="totalWeight" min="0.001" step="0.001" defaultValue={sale?.totalWeightKg || ""} required /></FormField><FormField label="Price per kg"><input type="number" name="pricePerKg" min="0.01" step="0.01" defaultValue={sale?.pricePerKg ?? ""} required /></FormField></> : <FormField label="Price per bird"><input type="number" name="pricePerBird" min="0.01" step="0.01" defaultValue={sale?.pricePerBird ?? ""} required /></FormField>}</div><FormField label="Notes"><textarea name="notes" defaultValue={sale?.notes ?? ""} rows={3} placeholder="Optional sale notes" /></FormField><div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "Saving..." : sale ? "Save changes" : "Record sale"}</button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></Card>;
}

function SaleRow({ sale, currency, onEdit }: { sale: Sale; currency: string; onEdit: () => void }) {
  const [state, action, pending] = useActionState(deleteSaleAction, empty);
  function remove() { if (window.confirm(`Delete sale for ${sale.batchCode}?`)) { const formData = new FormData(); formData.set("saleId", sale.id); void action(formData); } }
  return <div className="sale-row"><div className="sale-icon"><ShoppingCart size={16} /></div><div className="sale-main"><Link href={`/sales/${sale.id}`}><strong>{sale.batchCode}</strong></Link><span>{sale.buyer} <i /> {sale.date}</span></div><Badge tone={sale.paymentStatus === "PAID" ? "green" : sale.paymentStatus === "PARTIAL" ? "amber" : "red"}>{sale.paymentStatus ?? "UNPAID"}</Badge><strong>{money(sale.revenue, currency)}</strong><button type="button" className="icon-button" onClick={onEdit} aria-label={`Edit sale for ${sale.batchCode}`}><Edit3 size={15} /></button><button type="button" className="icon-button" onClick={remove} disabled={pending} aria-label={`Delete sale for ${sale.batchCode}`}><Trash2 size={15} /></button>{state.message && <small className="health-row-feedback">{state.message}</small>}</div>;
}

export function SalesManager({ farm, sales, batches, customers, summary, paymentSummary }: { farm: Farm; sales: Sale[]; batches: Batch[]; customers: Customer[]; summary: { revenue: number; birdsSold: number; saleCount: number; thisMonth: number; directExpenses: number; estimatedProfit: number }; paymentSummary: PaymentSummary }) {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Sale>();
  const filtered = sales.filter((sale) => `${sale.batchCode} ${sale.buyer}`.toLowerCase().includes(query.toLowerCase()));
  function create() { setEditing(undefined); setOpen(true); }
  return <><div className="page-heading"><div><p className="eyebrow">Farm revenue</p><h1>Sales</h1><p className="heading-subtitle">Track birds sold, buyers, revenue, and direct farm margin by batch.</p></div><Button onClick={create}><Plus size={17} /> Record sale</Button></div><div className="batch-summary-grid sales-summary"><Card><span>Total revenue</span><strong>{money(summary.revenue, farm.currency)}</strong><small>{summary.saleCount} sale records</small></Card><Card><span>Cash received</span><strong>{money(paymentSummary.totalPaid, farm.currency)}</strong><small>{paymentSummary.paidSales} paid sales</small></Card><Card><span>Outstanding</span><strong>{money(paymentSummary.totalOutstanding, farm.currency)}</strong><small>{paymentSummary.partialSales} partial · {paymentSummary.unpaidSales} unpaid</small></Card><Card><span>Estimated direct profit</span><strong>{money(summary.estimatedProfit, farm.currency)}</strong><small>Revenue less expenses</small></Card></div>{open && <SaleForm batches={batches.filter((batch) => batch.status === "active" || batch.code === editing?.batchCode)} customers={customers} sale={editing} onClose={() => setOpen(false)} />}<Card className="phase4-list-card"><SectionHeading eyebrow="Sales register" title="Recent sales" action={<span className="batch-list-meta">{filtered.length} shown</span>} /><div className="batch-toolbar"><label className="search-field"><Search size={16} /><input aria-label="Search sales" placeholder="Search batch or customer" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{filtered.length === 0 ? <EmptyState title="No sales found" message="Try another search or record the first sale." action={<Button onClick={create}><Plus size={16} /> Record sale</Button>} /> : <div className="sales-list">{filtered.map((sale) => <SaleRow key={sale.id} sale={sale} currency={farm.currency} onEdit={() => { setEditing(sale); setOpen(true); }} />)}</div>}</Card></>;
}