"use client";

import { useActionState, useState } from "react";
import Link from "next/link";
import { Check, Plus, Search, ShoppingCart, X } from "lucide-react";
import type { Batch, Farm, PaymentSummary, Sale } from "@/domain/types";
import { saleAction } from "@/app/sales/actions";
import { Badge, Button, Card, EmptyState, FormField, SectionHeading } from "@/components/ui";

type Customer = { id: string; name: string; phone?: string | null };
const empty = { ok: false, message: "" };
function money(value: number, currency: string) { return new Intl.NumberFormat("en-TZ", { style: "currency", currency, maximumFractionDigits: 0 }).format(value).replace("TZS", "TZS "); }
function Feedback({ state }: { state: { ok: boolean; message: string } }) { return state.message ? <div className={`form-feedback ${state.ok ? "feedback-success" : "feedback-error"}`} role="status">{state.ok ? <Check size={15} /> : <X size={15} />}{state.message}</div> : null; }

function SaleForm({ batches, customers, onClose }: { batches: Batch[]; customers: Customer[]; onClose: () => void }) {
  const [state, action, pending] = useActionState(saleAction, empty);
  const [mode, setMode] = useState("PER_KG");
  return <Card className="phase4-form"><div className="form-card-heading"><div><p className="eyebrow">Farm revenue</p><h2>Record sale</h2><p>Revenue is calculated and validated on the server.</p></div><button className="icon-button" onClick={onClose} aria-label="Close sale form"><X size={18} /></button></div><Feedback state={state} /><form action={action} className="batch-form"><div className="form-grid"><FormField label="Batch"><select name="batchId" required><option value="">Select batch</option>{batches.map((batch) => <option key={batch.id} value={batch.id}>{batch.code} · {batch.currentBirds.toLocaleString()} available</option>)}</select></FormField><FormField label="Customer"><select name="customerId"><option value="">Direct sale</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></FormField><FormField label="Sale date"><input type="date" name="date" defaultValue="2026-09-10" required /></FormField><FormField label="Birds sold"><input type="number" name="birdsSold" min="1" required /></FormField><FormField label="Pricing mode"><select name="pricingMode" value={mode} onChange={(event) => setMode(event.target.value)}><option value="PER_KG">Per kilogram</option><option value="PER_BIRD">Per bird</option></select></FormField>{mode === "PER_KG" ? <><FormField label="Total weight (kg)"><input type="number" name="totalWeight" min="0.001" step="0.001" required /></FormField><FormField label="Price per kg"><input type="number" name="pricePerKg" min="0.01" step="0.01" required /></FormField></> : <FormField label="Price per bird"><input type="number" name="pricePerBird" min="0.01" step="0.01" required /></FormField>}</div><FormField label="Notes"><textarea name="notes" rows={3} placeholder="Optional sale notes" /></FormField><div className="form-actions"><button className="button button-primary" disabled={pending}>{pending ? "Saving..." : "Record sale"}</button><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button></div></form></Card>;
}

export function SalesManager({ farm, sales, batches, customers, summary, paymentSummary }: { farm: Farm; sales: Sale[]; batches: Batch[]; customers: Customer[]; summary: { revenue: number; birdsSold: number; saleCount: number; thisMonth: number; directExpenses: number; estimatedProfit: number }; paymentSummary: PaymentSummary }) {
  const [query, setQuery] = useState(""); const [open, setOpen] = useState(false);
  const filtered = sales.filter((sale) => `${sale.batchCode} ${sale.buyer}`.toLowerCase().includes(query.toLowerCase()));
  return <><div className="page-heading"><div><p className="eyebrow">Farm revenue</p><h1>Sales</h1><p className="heading-subtitle">Track birds sold, buyers, revenue, and direct farm margin by batch.</p></div><Button onClick={() => setOpen(true)}><Plus size={17} /> Record sale</Button></div><div className="batch-summary-grid sales-summary"><Card><span>Total revenue</span><strong>{money(summary.revenue, farm.currency)}</strong><small>{summary.saleCount} sale records</small></Card><Card><span>Cash received</span><strong>{money(paymentSummary.totalPaid, farm.currency)}</strong><small>{paymentSummary.paidSales} paid sales</small></Card><Card><span>Outstanding</span><strong>{money(paymentSummary.totalOutstanding, farm.currency)}</strong><small>{paymentSummary.partialSales} partial · {paymentSummary.unpaidSales} unpaid</small></Card><Card><span>Estimated direct profit</span><strong>{money(summary.estimatedProfit, farm.currency)}</strong><small>Revenue less expenses</small></Card></div>{open && <SaleForm batches={batches.filter((batch) => batch.status === "active")} customers={customers} onClose={() => setOpen(false)} />}<Card className="phase4-list-card"><SectionHeading eyebrow="Sales register" title="Recent sales" action={<span className="batch-list-meta">{filtered.length} shown</span>} /><div className="batch-toolbar"><label className="search-field"><Search size={16} /><input aria-label="Search sales" placeholder="Search batch or customer" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div>{filtered.length === 0 ? <EmptyState title="No sales found" message="Try another search or record the first sale." action={<Button onClick={() => setOpen(true)}><Plus size={16} /> Record sale</Button>} /> : <div className="sales-list">{filtered.map((sale) => <div className="sale-row" key={sale.id}><div className="sale-icon"><ShoppingCart size={16} /></div><div className="sale-main"><Link href={`/sales/${sale.id}`}><strong>{sale.batchCode}</strong></Link><span>{sale.buyer} <i /> {sale.date}</span></div><div className="sale-metric"><span>Birds</span><strong>{sale.birds.toLocaleString()}</strong></div><div className="sale-metric"><span>Paid</span><strong>{money(sale.paidAmount ?? 0, farm.currency)}</strong></div><div className="sale-revenue"><span>Balance</span><strong>{money(sale.balanceDue ?? sale.revenue, farm.currency)}</strong></div><Badge tone={sale.paymentStatus === "PAID" ? "green" : sale.paymentStatus === "PARTIAL" ? "amber" : "red"}>{sale.paymentStatus ?? "UNPAID"}</Badge></div>)}</div>}</Card></>;
}