"use client";

import { Check, Languages, MapPin, Moon, Sun, UserRound, Laptop } from "lucide-react";
import type { Farm, User } from "@/domain/types";
import { useLanguage } from "@/lib/i18n/language-provider";
import { useTheme, type Theme } from "@/lib/theme-provider";
import type { Language } from "@/lib/i18n/locales";
import { Badge, Card, SectionHeading } from "@/components/ui";

export function SettingsManager({ farm, user }: { farm: Farm; user: User }) {
  const { language, setLanguage, t } = useLanguage();
  const { theme, setTheme } = useTheme();
  const appearanceOptions: Array<[Theme, typeof Sun, string, string]> = [["light", Sun, t.settings.light, t.settings.lightDescription], ["dark", Moon, t.settings.dark, t.settings.darkDescription], ["system", Laptop, t.settings.system, t.settings.systemDescription]];
  return <><div className="page-heading"><div><p className="eyebrow">{t.settings.eyebrow}</p><h1>{t.settings.title}</h1><p className="heading-subtitle">{t.settings.description}</p></div></div><div className="settings-grid"><Card><SectionHeading eyebrow="Language" title={t.settings.languageTitle} /><p className="settings-description">{t.settings.languageDescription}</p><div className="language-selector" role="group" aria-label={t.common.language}>{([['en', t.common.english], ['sw', t.common.kiswahili]] as const).map(([value, label]) => <button key={value} className={language === value ? "language-option language-option-active" : "language-option"} onClick={() => setLanguage(value as Language)} aria-pressed={language === value}><Languages size={17} /><span>{label}</span>{language === value && <Check size={15} />}</button>)}</div><p className="settings-saved"><Check size={14} /> {t.settings.saved}</p></Card><Card><SectionHeading eyebrow="Appearance" title={t.settings.appearanceTitle} /><p className="settings-description">{t.settings.appearanceDescription}</p><div className="appearance-selector" role="radiogroup" aria-label={t.settings.appearanceTitle}>{appearanceOptions.map(([value, Icon, title, description]) => <button key={value} className={theme === value ? "appearance-option appearance-option-active" : "appearance-option"} onClick={() => setTheme(value)} role="radio" aria-checked={theme === value}><Icon size={17} /><div><strong>{title}</strong><small>{description}</small></div>{theme === value && <Check size={15} />}</button>)}</div></Card><Card><SectionHeading eyebrow="Farm" title={t.settings.farmTitle} /><p className="settings-description">{t.settings.farmDescription}</p><div className="settings-info-list"><div><strong>{t.settings.farmName}</strong><span>{farm.name}</span></div><div><strong>{t.settings.location}</strong><span><MapPin size={13} /> {farm.location}</span></div><div><strong>{t.settings.currency}</strong><span>{farm.currency}</span></div><div><strong>{t.settings.timezone}</strong><span>{farm.timezone}</span></div></div></Card><Card><SectionHeading eyebrow="Account" title={t.settings.accountTitle} /><p className="settings-description">{t.settings.accountDescription}</p><div className="settings-account"><div className="settings-account-avatar"><UserRound size={18} /></div><div><strong>{user.name}</strong><span>{user.role}</span></div></div><Badge tone="green">{t.common.selected}</Badge></Card></div></>;
}