"use client";

import Link from "next/link";
import { Check, Eye, EyeOff, Leaf, LockKeyhole, Mail, UserRound } from "lucide-react";
import { useActionState, useState } from "react";
import { useLanguage } from "@/lib/i18n/language-provider";
import { signupAction, type AuthActionState } from "@/app/signup/actions";

const emptyState: AuthActionState = { ok: false, message: "" };

export default function SignupPage() {
  const { language, setLanguage, t } = useLanguage();
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [state, formAction, pending] = useActionState(signupAction, emptyState);

  return <main className="auth-page auth-page-signup">
    <section className="auth-visual" aria-label={t.auth.brandDescription}><div className="auth-visual-glow" /><div className="auth-brand-row"><div className="auth-logo"><span>🐔</span></div><div><strong>Kuku<span>Dhamini</span></strong><small>{t.auth.brandTagline}</small></div></div><div className="auth-visual-content"><p className="auth-kicker"><Leaf size={15} /> {t.auth.createFarm}</p><h2>Bring clarity to every flock cycle.</h2><p>{t.auth.createFarmDescription}</p><ul>{[t.auth.trackBatches, t.auth.monitorHealth, t.auth.manageCosts, t.auth.followMoney].map((item) => <li key={item}><Check size={15} />{item}</li>)}</ul></div><div className="auth-visual-footer"><Leaf size={15} /> {t.auth.brandTagline}</div></section>
    <section className="auth-form-side"><div className="auth-language" role="group" aria-label={t.common.language}><button type="button" className={language === "en" ? "auth-language-active" : ""} onClick={() => setLanguage("en")}>English</button><button type="button" className={language === "sw" ? "auth-language-active" : ""} onClick={() => setLanguage("sw")}>Kiswahili</button></div><div className="auth-card auth-card-tall"><div className="auth-card-mark"><UserRound size={18} /></div><p className="eyebrow">{t.auth.createFarm}</p><h1>{t.auth.signUpTitle}</h1><p className="auth-card-subtitle">{t.auth.signUpSubtitle}</p><form action={formAction} className="auth-form" aria-label={t.auth.signUpTitle}>{state.message ? <div className="form-feedback error" role="alert">{state.message}</div> : null}<label className="form-field"><span>{t.auth.fullNameLabel}</span><div className="input-wrap"><UserRound size={17} aria-hidden="true" /><input name="name" type="text" autoComplete="name" placeholder={t.auth.nameHint} aria-label={t.auth.fullNameLabel} required /></div></label><label className="form-field"><span>{t.auth.emailLabel}</span><div className="input-wrap"><Mail size={17} aria-hidden="true" /><input name="email" type="email" autoComplete="email" placeholder={t.auth.emailHint} aria-label={t.auth.emailLabel} required /></div></label><div className="auth-form-section"><span>{t.auth.farmDetails}</span><small>{t.auth.trustNote}</small></div><label className="form-field"><span>{t.auth.passwordLabel}</span><div className="input-wrap"><LockKeyhole size={17} aria-hidden="true" /><input name="password" type={showPassword ? "text" : "password"} autoComplete="new-password" placeholder={t.auth.passwordHint} aria-label={t.auth.passwordLabel} required /><button type="button" className="password-toggle" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((value) => !value)}>{showPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div><small className="field-hint">{t.auth.passwordRequirement}</small></label><label className="form-field"><span>{t.auth.confirmPasswordLabel}</span><div className="input-wrap"><LockKeyhole size={17} aria-hidden="true" /><input name="confirmPassword" type={showConfirmPassword ? "text" : "password"} autoComplete="new-password" placeholder={t.auth.confirmPasswordHint} aria-label={t.auth.confirmPasswordLabel} required /><button type="button" className="password-toggle" aria-label={showConfirmPassword ? "Hide password" : "Show password"} onClick={() => setShowConfirmPassword((value) => !value)}>{showConfirmPassword ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><button className="button button-primary auth-submit" disabled={pending} type="submit">{pending ? t.auth.creating : t.auth.createAccount}</button></form><p className="auth-switch">{t.auth.alreadyHaveAccount} <Link href="/login">{t.common.login}</Link></p></div></section>
  </main>;
}
